# Generated by Django 2.2 on 2021-03-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
    ]
